---
- name: IOS XE Compliance
  hosts: "{{ _hosts | default('ios') }}"
  gather_facts: false
  vars:
    ignore_all_errors: false
    ansible_command_timeout: 60
  roles:
    - demo.compliance.iosxeSTIG
